version: '3.0'

services:

  ui:
    container_name: ui
    restart: always
    image: ${REGISTRY_HOST}/dockertest-pipeline-ui:latest
    build:
      context: ./ui
      dockerfile: Dockerfile
      target: ${TARGET}
    volumes:
      - ./ui:/app:delegated
      - /app/node_modules
    ports:
      - '8080:8080'
      - '80:80'

  backend:
    container_name: backend
    restart: always
    image: ${REGISTRY_HOST}/dockertest-pipeline-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: ${TARGET}
    volumes:
      - ./backend:/app:delegated
      - /app/node_modules
    ports:
      - '8081:8081'