version: 2
jobs:
  build:
    docker:
      - image: node:11.10.1

    working_directory: ~/repo
    
    environment:
      NODE_ENV: development
      TARGET: dev

    steps:
      - checkout
      - run:
          name: Run unit tests
          command: echo 'running tests here'

